### ISSUE TITLE
PHP notice - undefined index for login url

### ISSUE THREAD

**Issue by dflitner** [Apps-and-Design/d7_commponent_header#2]
I get this notice after editing the header component block.
`Notice: Undefined index: asu_component_header_login_url in asu_component_header_block_save() (line 578 of /code/sites/all/modules/contrib/asu_component_header/asu_component_header.module).`

(My line number will be different because I've got extra blocks in here.)

**Comment by dflitner** [comment]
It's on line 143. Here is the fix:
Change
`$form['asu_component_header']['asu_component_login_url'] = array(`
to
`$form['asu_component_header']['asu_component_header_login_url'] = array(`

**Comment by mlsamuelson** [comment]
Awesome, @dflitner ! Fix committed. https://github.com/Apps-and-Design/d7_commponent_header/commit/1bd7a727bcb54c521bc1f49de24e36d2cf9f06fe
