### ISSUE TITLE
PHP Warning: Use of undefined constant ASU_BRAND_SITE_MENU_NAME_DEFAULT

### ISSUE THREAD

**Issue by dflitner** [Apps-and-Design/d7_commponent_header#3]
`Warning:  Use of undefined constant ASU_BRAND_SITE_MENU_NAME_DEFAULT - assumed  'ASU_BRAND_SITE_MENU_NAME_DEFAULT' (this will throw an Error in a future  version of PHP) in asu_component_header_block_configure() (line 135 of /code/sites/all/modules/contrib/asu_component_header/asu_component_header.module).`

I made the warning go away by changing the default value for asu_component_header_sitemenu_name to 'main-menu'.
`'#default_value' => variable_get('asu_component_header_sitemenu_name', 'main-menu'),`

**Comment by mlsamuelson** [comment]
Great find @dflitner! Fix committed. Thank you!
https://github.com/Apps-and-Design/d7_commponent_header/commit/477b37e2138e7e6b2bdbb8b2cd1a32181313e807
