### ISSUE TITLE
Update footer links per Sarah's message

### ISSUE THREAD

**Issue by dflitner** [Apps-and-Design/d7_commponent_header#4]
Sarah posted: Some of the links in the footer have changed, there are redirects in place, but please update at your earliest convenience.

Here is an updated asu_component_header.module file with the new links. (renamed to txt so it will upload)

[asu_component_header.txt](https://github.com/Apps-and-Design/d7_commponent_header/files/7079583/asu_component_header.txt)

**Comment by mlsamuelson** [comment]
Hi Debbie. Circling back around to this. Any chance you can submit a Pull Request? If it doesn't look like you can (I haven't dug very deep into the settings, but looks like you ought to be able to), what you might be able to do is fork the repo, and then submit a Pull Request from the fork. https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by dflitner** [comment]
I can't create a branch and push it up:
remote: Permission to Apps-and-Design/d7_commponent_header.git denied to dflitner.

So I will try to do the fork PR.

**Comment by dflitner** [comment]
Looks like that worked :)

**Comment by mlsamuelson** [comment]
PR merged. Thanks!
